name: Deploy Static Docs

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy `/tools` via SCP
    runs-on: ubuntu-22.04

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      SSH_HOST:        ${{ secrets.SSH_HOST }}
      SSH_USER:        ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Set target path based on branch
        id: path
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "dir=${{ secrets.SSH_TARGET_DIR_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "dir=${{ secrets.SSH_TARGET_DIR_DEV }}" >> $GITHUB_OUTPUT
          fi

      - name: Copy `.` via rsync
        run: |
          rsync -avz \
            --partial \
            --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.gitignore' \
            --exclude='.gitattributes' \
            --exclude='.DS_Store' \
            --exclude='css/' \
            --exclude='img/' \
            --exclude='README.md/' \
            -e "ssh -i ~/.ssh/id_rsa" \
            . \
            "${SSH_USER}@${SSH_HOST}:${{ steps.path.outputs.dir }}/"
